"""API Error Code Catalog."""

from enum import Enum


class APIErrorCode(str, Enum):
    # Authentication & Authorization
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    TENANT_MISMATCH = "TENANT_MISMATCH"

    # Validation & Parameters
    INVALID_PARAMETER = "INVALID_PARAMETER"
    MISSING_PARAMETER = "MISSING_PARAMETER"

    # Resource & Logic
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"

    # Service & Execution
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    EXTERNAL_PROVIDER_ERROR = "EXTERNAL_PROVIDER_ERROR"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
