/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/search': typeof SearchRoute
  '/twin': typeof TwinRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/search': typeof SearchRoute
  '/twin': typeof TwinRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/compliance': typeof ComplianceRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/graph': typeof GraphRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/search': typeof SearchRoute
  '/twin': typeof TwinRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/chat'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/graph'
    | '/investigations'
    | '/login'
    | '/maintenance'
    | '/search'
    | '/twin'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/chat'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/graph'
    | '/investigations'
    | '/login'
    | '/maintenance'
    | '/search'
    | '/twin'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/chat'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/graph'
    | '/investigations'
    | '/login'
    | '/maintenance'
    | '/search'
    | '/twin'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ChatRoute: typeof ChatRoute
  ComplianceRoute: typeof ComplianceRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  GraphRoute: typeof GraphRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SearchRoute: typeof SearchRoute
  TwinRoute: typeof TwinRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ChatRoute: ChatRoute,
  ComplianceRoute: ComplianceRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  GraphRoute: GraphRoute,
  InvestigationsRoute: InvestigationsRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  SearchRoute: SearchRoute,
  TwinRoute: TwinRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
